server:
  port: 8085
  servlet:
    context-path: /user

spring:
  application:
    name: user-service
  #db
  datasource:
    url: jdbc:mysql://localhost:3306/testing_demo_user
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#logs
logging:
  level:
    com:
      debug:
      zaxxer:
        hikari: error
    org: error

#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/
